[package]
name = "reb"
version = "0.1.0"
authors = ["Matt Traudt <sirmatt@ksu.edu>"]
edition = "2018"

[dependencies]
structopt = "0.2"
log = "0.4"
env_logger = "0.6"
config = { version = "0.9", features = ["toml"], default-features = false }
chrono = "0.4"
tempfile = "3.0"
rand = "0.6"
