[strings]
blog_title = "My First Blog"
blog_subtitle = "Where I write about things and stuff"
blog_author = "John Doe"

[paths]
post_dname = "posts"
build_dname = "build"
# Can also be /path/to/parser
parse_bin = "cmark"
# Will be copied to /static/img/header.jpg
blog_img_fname = "cats.jpg"
favicon_fname = "favicon.png"
